#!/usr/bin/env python3
"""Generate original (legal-to-redistribute) sample HUS and VIP files.

The design is a parametric rose curve generated from mathematics, so the
resulting files are original works created for this repository. Streams are
compressed with the reference C++ ArchiveLib implementation at level 4.
"""
import json, math, os, struct, subprocess, hashlib

REFCLI, OUT = "/tmp/refcli", "/tmp/fixtures"

def ref(mode, level, data: bytes) -> bytes:
    open("/tmp/fixgen/in.bin", "wb").write(data)
    r = subprocess.run([REFCLI, mode, str(level), "/tmp/fixgen/in.bin", "/tmp/fixgen/out.bin"], capture_output=True)
    assert r.returncode == 0, r.stderr.decode()
    return open("/tmp/fixgen/out.bin", "rb").read()

def clamp8(v): return max(-127, min(127, int(round(v))))

# --- design: 3-petal rose, two colours ---
def build_design():
    xs, ys, attrs = [], [], []
    px, py = 0.0, 0.0
    def moveto(x, y, cmd):
        nonlocal px, py
        dx, dy = clamp8(x - px), clamp8(y - py)
        px, py = px + dx, py + dy
        xs.append(dx & 0xFF); ys.append(dy & 0xFF); attrs.append(cmd)
    n = 600
    for i in range(n):
        t = math.pi * i / (n - 1)
        r = 120 * math.sin(3 * t)
        moveto(r * math.cos(t), r * math.sin(t), 0x80)  # STITCH
    moveto(0, 0, 0x84)  # COLOR_CHANGE
    for i in range(240):
        t = 2 * math.pi * i / 239
        moveto(40 * math.cos(t), 40 * math.sin(t), 0x80)
    moveto(0, 0, 0x90)  # END
    return bytes(attrs), bytes(xs), bytes(ys)

attrs, xs, ys = build_design()
nstitch, ncolors = len(attrs), 2
minx = miny = 0; maxx = maxy = 0
x = y = 0
for i in range(nstitch):
    dx = xs[i] - 256 if xs[i] >= 128 else xs[i]
    dy = ys[i] - 256 if ys[i] >= 128 else ys[i]
    x += dx; y += dy
    minx, maxx, miny, maxy = min(minx,x), max(maxx,x), min(miny,y), max(maxy,y)

c_attr, c_x, c_y = (ref("c", 4, s) for s in (attrs, xs, ys))

# --- HUS ---
# header layout per pyembroidery HusReader / EmbroidePy
HUS_MAGIC = 0x00C8AF5B
hdr_size = 42 + 2 * ncolors
cmd_off = hdr_size
x_off = cmd_off + len(c_attr)
y_off = x_off + len(c_x)
hus = struct.pack("<iii4h iii 8s h", HUS_MAGIC, nstitch, ncolors, maxx, maxy, minx, miny,
                  cmd_off, x_off, y_off, b"rose\x00\x00\x00\x00", 0)
hus += struct.pack("<2h", 24, 5)  # thread-set indices
hus += c_attr + c_x + c_y
open(f"{OUT}/rose.hus", "wb").write(hus)

# --- VIP ---
# header layout per Embroidermodder libembroidery readVip
VIP_MAGIC = 0x0190FC5D
vipDecodingTable = bytes([
0x2E,0x82,0xE4,0x6F,0x38,0xA9,0xDC,0xC6,0x7B,0xB6,0x28,0xAC,0xFD,0xAA,0x8A,0x4E,
0x76,0x2E,0xF0,0xE4,0x25,0x1B,0x8A,0x68,0x4E,0x92,0xB9,0xB4,0x95,0xF0,0x3E,0xEF,
0xF7,0x40,0x24,0x18,0x39,0x31,0xBB,0xE1,0x53,0xA8,0x1F,0xB1,0x3A,0x07,0xFB,0xCB])
colors = [(226, 32, 60), (255, 200, 40)]
decoded = b"".join(bytes([r_, g, b_, 1]) for (r_, g, b_) in colors)
# writer-side chaining (inverse of readVip decode)
encoded = bytearray(); prev = 0
for i, byte in enumerate(decoded):
    prev = (byte ^ vipDecodingTable[i] ^ prev) & 0xFF
    encoded.append(prev)
color_block = bytes(encoded)
attr_off = 46 + len(color_block) + 4 * (ncolors + 1) + 6  # mimic real writer padding
x_off_v = attr_off + len(c_attr)
y_off_v = x_off_v + len(c_x)
vip = struct.pack("<iii4h iii 8s h i", VIP_MAGIC, nstitch, ncolors, maxx, maxy, minx, miny,
                  attr_off, x_off_v, y_off_v, b"rose\x00\x00\x00\x00", 0, len(color_block))
vip += color_block
vip += struct.pack("<%di" % (ncolors + 1), *([1] * (ncolors + 1)))
vip += struct.pack("<ih", 0, 0)
assert len(vip) == attr_off, (len(vip), attr_off)
vip += c_attr + c_x + c_y
open(f"{OUT}/rose.vip", "wb").write(vip)

# golden stream fixtures for the synthetic design
man = json.load(open(f"{OUT}/manifest.json"))
for key, comp, raw in [("attr", c_attr, attrs), ("x", c_x, xs), ("y", c_y, ys)]:
    name = f"vip_rose_{key}"
    open(f"{OUT}/{name}.cmp", "wb").write(comp)
    open(f"{OUT}/{name}.out", "wb").write(raw)
    man.append({"name": name, "level": 4,
        "compressedFile": f"{name}.cmp", "expectedFile": f"{name}.out",
        "compressedLength": len(comp), "expectedLength": len(raw),
        "expectedSha256": hashlib.sha256(raw).hexdigest(),
        "description": f"{key} stream of the synthetic 'rose' design as stored in rose.vip/rose.hus.",
        "source": "original parametric design generated by tools/generate-fixtures; compressed with the reference C++ implementation"})
json.dump(man, open(f"{OUT}/manifest.json", "w"), indent=2)
print("rose.hus", len(hus), "rose.vip", len(vip), "stitches", nstitch)
